### ISSUE TITLE
DELPHI_Server doesn't exist.

### ISSUE THREAD

**Issue by fatancy2580** [lucian-ilie/DELPHI#5]
Hi! Thanks for your work！And l have a question.
Your README.md require to git checkout DELPHI_Server,however DELPHI_Server doesn't exist.
Looking foward to your reply.Thank you again

**Comment by yiweili** [comment]
Thank you for the message. The branch DELPHI_Server is for the SPRINT program not DELPHI. Please see the branch here:
https://github.com/lucian-ilie/SPRINT/tree/DELPHI_Server

**Comment by fatancy2580** [comment]
> Thank you for the message. The branch DELPHI_Server is for the SPRINT program not DELPHI. Please see the branch here:
> https://github.com/lucian-ilie/SPRINT/tree/DELPHI_Server

Thank you for your answer
